#!/bin/bash
# pay attention that does not math any albumID

cd $HOME/Desktop/gmphoto
if [ -n "$1" ]; then myout="gmphoto"$1; else myout="gmphoto"; fi
if [ -n "$2" ]; then mydate=$2; else mydate=`date "+%Y%m%d"`; fi

rm $myout
ptok=""
ndd=0
zy=${mydate:0:4}
zm=${mydate:4:2}
zd=${mydate:6:2};
myaux="aux."$RANDOM"."$RANDOM
for ((;;)) do
  
  tok=`cat token`
  curl -s -L --request POST \
  --header "Authorization: Bearer $tok" \
  --header "Content-Type: application/json" \
  --data '{"pageSize":100,"filters":{"dateFilter":{"dates":[{"year":'$zy',"month":'$zm',"day":'$zd'}]}},"pageToken":"'$ptok'"}' \
  https://photoslibrary.googleapis.com/v1/mediaItems:search > $myaux
    
  ndl=`cat $myaux | grep baseUrl | wc -l | awk '{print $1}'`
  ndd=$((ndd+ndl))
  cat $myaux | jq -r ".mediaItems[] | [.description,.productUrl,.baseUrl,.mediaMetadata.creationTime,.id,.filename] | @csv" | tr -d '"' >> $myout
  ptok=`cat $myaux | jq -r ".nextPageToken"`
  echo $ndd
  if [ ${#ptok} -le 5 ]; then break; fi
done

sort -k1,7 -o $myout $myout
