#!/bin/bash

cd $HOME/Desktop/gmphoto
if [ -n "$1" ]; then myout="gmphoto"$1; else myout="gmphoto"; fi

rm $myout
ptok=""
ndd=0
myaux="aux."$RANDOM"."$RANDOM
for ((;;)) do

  tok=`cat token`
  curl -s -L --request POST \
  --header "Authorization: Bearer $tok" \
  --header "Content-Type: application/json" \
  --data '{"pageSize":100,"albumId":"AAe248ZKwc1oAs9V4kqTd4dXz-cdvEj8IYEZ3V-r1ZBKjxSQ9lfunPlEU6H2Y3KhTtswyRuo5NDa","pageToken":"'$ptok'"}' \
  https://photoslibrary.googleapis.com/v1/mediaItems:search > $myaux
    
  ndl=`cat $myaux | grep baseUrl | wc -l | awk '{print $1}'`
  ndd=$((ndd+ndl))
  cat $myaux | jq -r ".mediaItems[] | [.description,.productUrl,.baseUrl,.mediaMetadata.creationTime,.id,.filename] | @csv" | tr -d '"' >> $myout
  ptok=`cat $myaux | jq -r ".nextPageToken"`
  echo $ndd
  if [ ${#ptok} -le 5 ]; then break; fi
done
