#!/bin/bash

# takeout only of Google Photo only of Salemi Archivio
# unzip on $HOME/Desktop/gmphoto

cd $HOME/Desktop/gmphoto
mv "Takeout/Google Photos/Photos from 2021/"* "Takeout"
mv "Takeout/Google Photos/Photos from 2022/"* "Takeout"
rm -rf "Takeout/Google Photos/"
rm Takeout/*.mp4*
rm Takeout/*.html
mypath="Takeout"
myrep="backup"

mylast="";
ls -r "$mypath/"*".jpg" |  while read fff; do
  myname=`echo $fff | awk -F "/" '{print $4}'`
  myorg="$myname"
  echo $myname
  mysec=`echo $myname | awk -F "." '{print $1"-edited."$2}'`
  if [ -f "$mypath/$mysec" ]; then myname="$mysec"; fi
  if [ "$myname" = "$mylast" ]; then 
    continue
  else
    mydob=`echo $myorg | awk -F"[()]" '{print $2}'`
    if ((mydob>0)); then
      myxx=`echo $myorg | awk -F"[()]" '{print $1$3"("$2").json"}'`
    else
      myxx="$myorg.json"
    fi
    mytarget=`cat "$mypath/$myxx" | jq -r ".description"`
  fi
  mylast="$myname"
  mytarget=${mytarget:0:7}
  cp "$mypath/$myname" "$myrep/$mytarget.jpg"  
  echo ".."$mytarget
done
