#!/bin/bash

cd $HOME/Desktop/gmphoto
rm gmphoto
ptok=""

for ((;;)) do

  tok=`cat token`
  curl -s -L --request POST \
  --header "Authorization: Bearer $tok" \
  --header "Content-Type: application/json" \
  --data '{"pageSize":50,"albumId":"AAe248ZKwc1oAs9V4kqTd4dXz-cdvEj8IYEZ3V-r1ZBKjxSQ9lfunPlEU6H2Y3KhTtswyRuo5NDa","pageToken":"'$ptok'"}' \
  https://photoslibrary.googleapis.com/v1/mediaItems:search > aux1
  
  cat aux1 | jq -r ".mediaItems[] | [.description,.productUrl,.baseUrl,.mediaMetadata.creationTime,.id,.filename] | @csv" | tr -d '"' >> gmphoto
  ptok=`cat aux | jq -r ".nextPageToken"`
  if [ ${#ptok} -le 5 ]; then break; fi
done
