#!/bin/bash

cd $HOME/Desktop/gmphoto
tok=`cat token`

curl -s --get \
--header "Authorization: Bearer $tok" \
--data "majorDimension=ROWS" \
$'https://sheets.googleapis.com/v4/spreadsheets/1llfQf5gKJWKQ2v26qQWLik-P74F1QI2cu2iopM0uhC0/values/Quadri!A2:G' > aux1

rm aux2
cat aux1 | jq -r ".values[] | @csv" | tr -d '"' | while IFS=, read -r myid myx myx myx myx myx mycrea; do
  lmycrea=${#mycrea}
  if ((lmycrea>10)); then
    ddd=`echo $mycrea | tr "TZ" " "`
    mys=`date -j -f "%Y-%m-%d %H:%M:%S " +%s "$ddd"`; echo "$myid,$mys" >> aux2 
  fi 
done

rm aux3
cat gmphoto | while IFS=, read -r myid myx myx mycrea googleid myx; do
  lmyid=${#myid}
  lmycrea=${#mycrea}
  if ((lmyid<4 && lmycrea>10)); then 
    ddd=`echo $mycrea | tr "TZ" " "`
    mys=`date -j -f "%Y-%m-%d %H:%M:%S " +%s "$ddd"`
    echo "$googleid,$mys" >> aux3 
  fi
done

rm aux4
cat aux3 | while IFS=, read -r myid mys; do 
  mm=100000000
  myid2=""
  cat aux2 | while IFS=, read -r myid1 mys1; do 
    d=$((mys-mys1))
    if ((d<0)); then d=$((-d)); fi; 
    if ((d<mm)); then mm=$d; myid2=$myid1; fi; 
    echo "mm=$mm;myid2=$myid2" > aux5
  done 
  . aux5 
  echo "$myid,$myid2,$mm" >> aux4

done

cat aux4 | while IFS=, read -r myid myl mys; do
  tok=`cat token`
  mylabel="MTS"$myl
  
  curl -s -L --request PATCH \
  --header "Authorization: Bearer $tok" \
  --header "Content-Type: application/json" \
  --data '{"description":"'$mylabel'"}' \
  $'https://photoslibrary.googleapis.com/v1/mediaItems/'$myid'?updateMask=description'
  
  sleep 5
done
