#!/bin/bash

cd $HOME/Desktop/gmphoto
myrep="backup"
mycloud="/Users/gmazzini/quadrisalemi"

ls -r "$myrep/"*".jpg" |  while read fff; do
  myname=`echo $fff | awk -F "/" '{print $2}'`
  echo $myname
  if [ -f "$mycloud/$myname" ]; then 
    cp "$myrep/$myname" "$mycloud/$myname"
    echo "backuped"; 
  fi
done
