#!/bin/bash

cd $HOME/Desktop/gmphoto

. googlephoto/albumdatadownload B

tok=`cat token`
curl -s --get \
--header "Authorization: Bearer $tok" \
--data "majorDimension=ROWS" \
$'https://sheets.googleapis.com/v4/spreadsheets/1llfQf5gKJWKQ2v26qQWLik-P74F1QI2cu2iopM0uhC0/values/Quadri!A2:F' > auxB2

rm auxB3
cat auxB2 | jq -r ".values[] | @csv" | tr -d '"' | while IFS=, read -r myid myx mytitle myxx myyy mydest; do
  if [[ $mydest != "Archivio" ]]; then mydest="Non Disponibile"; fi
  echo "MTS"$myid" - "$mytitle" - "$myxx"x"$myyy" - "$mydest >> auxB3
done

cat gmphotoB | while IFS=, read -r myid myx myx myx googleid myx; do
  lmyid=${#myid}
  if ((lmyid==7)); then
    mylabel=`grep $myid auxB3`
    echo $mylabel

    tok=`cat token`        
    curl -s -L --request PATCH \
    --header "Authorization: Bearer $tok" \
    --header "Content-Type: application/json" \
    --data "{\"description\":\"$mylabel\"}" \
    "https://photoslibrary.googleapis.com/v1/mediaItems/$googleid?updateMask=description"
    
    sleep 3
  fi
done
