#!/bin/bash

cd $HOME/Desktop/gmphoto

. googlephoto/albumdatadownload C

tok=`cat token`
curl -s --get \
--header "Authorization: Bearer $tok" \
--data "majorDimension=ROWS" \
$'https://sheets.googleapis.com/v4/spreadsheets/1llfQf5gKJWKQ2v26qQWLik-P74F1QI2cu2iopM0uhC0/values/Quadri!A2:F' > auxC2

cat auxC2 | jq -r ".values[] | @csv" | tr -d '"' | while IFS=, read -r myid myx mytitle myxx myyy mydest; do
  mylabel="MTS"$myid
  mycheck=`grep $mylabel gmphotoC`
  lmycheck=${#mycheck}
  if ((lmycheck<7)); then
  
    orgname=$mylabel".jpg"
    wn="backup/"$orgname
    if [[ -f "$wn" ]]; then
    
      tok=`cat token`
      curl -s --request POST -L \
      --header "Authorization: Bearer $tok" \
      --header "Content-type: application/octet-stream" \
      --header "X-Goog-Upload-Content-Type: image/jpeg" \
      --header "X-Goog-Upload-Protocol: raw" \
      --data-binary "@"$wn \
      "https://photoslibrary.googleapis.com/v1/uploads" > auxC3
    
      uptoken=`cat auxC3`
      tok=`cat token`
      curl -s --request POST -L \
      --header "Authorization: Bearer $tok" \
      --header "Content-Type: application/json" \
      --data '{"albumId":"AAe248ZKwc1oAs9V4kqTd4dXz-cdvEj8IYEZ3V-r1ZBKjxSQ9lfunPlEU6H2Y3KhTtswyRuo5NDa","newMediaItems":[{"description":"'$mylabel'","simpleMediaItem":{"uploadToken":"'$uptoken'","fileName":"'$orgname'"}}]}' \
      $'https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate'
      
      sleep 3
    else 
      echo "Missed "$mylabel
    fi
  fi
done
