#!/bin/bash

cd $HOME/Desktop/gmphoto
rm gmphoto
ptok=""

for ((;;)) do

  tok=`cat token`
  curl -s -L --request POST \
  --header "Authorization: Bearer $tok" \
  --header "Content-Type: application/json" \
  --data '{"pageSize":50,"albumId":"AAe248ZKwc1oAs9V4kqTd4dXz-cdvEj8IYEZ3V-r1ZBKjxSQ9lfunPlEU6H2Y3KhTtswyRuo5NDa","pageToken":"'$ptok'"}' \
  "https://photoslibrary.googleapis.com/v1/mediaItems:search" > auxB1
  
  cat auxB1 | jq -r ".mediaItems[] | [.description,.productUrl,.baseUrl,.mediaMetadata.creationTime,.id,.filename] | @csv" | tr -d '"' >> gmphoto
  ptok=`cat auxB1 | jq -r ".nextPageToken"`
  if [ ${#ptok} -le 5 ]; then break; fi
done

tok=`cat token`
curl -s --get \
--header "Authorization: Bearer $tok" \
--data "majorDimension=ROWS" \
$'https://sheets.googleapis.com/v4/spreadsheets/1llfQf5gKJWKQ2v26qQWLik-P74F1QI2cu2iopM0uhC0/values/Quadri!A2:F' > auxB2

exit

rm auxB3
cat auxB2 | jq -r ".values[] | @csv" | tr -d '"' | while IFS=, read -r myid myx mytitle myxx myyy mydest; do
  if [[ $mydest != "Archivio" ]]; then mydest="Non Disponibile"; fi
  echo "MTS"$myid" - "$mytitle" - "$myxx"x"$myyy" - "$mydest >> auxB3
done

tail -r gmphoto | while IFS=, read -r myid myx myx myx googleid myx; do
  lmyid=${#myid}
  if ((lmyid==7)); then
    mylabel=`grep $myid auxB3`

    tok=`cat token`        
    curl -s -L --request PATCH \
    --header "Authorization: Bearer $tok" \
    --header "Content-Type: application/json" \
    --data "{\"description\":\"$mylabel\"}" \
    "https://photoslibrary.googleapis.com/v1/mediaItems/$googleid?updateMask=description"
    
    sleep 3
  fi
done
