#!/bin/bash

cd $HOME/Desktop/gmphoto
if [ -n "$1" ]; then mystart=$1; else mystart=1; fi
echo "mystart=$mystart" > aux50

. googlephoto/albumdatadownload G
. aux50

tail -n +$mystart gmphotoG > gmphotoE
rm gmspli*
split -l 200 gmphotoE gmsplit
gstart=$mystart
for fff in gmspli*; do
  echo -n "[" > aux
  cat $fff | awk -F "," '{if(length($2)>10){if(NR>1)printf(",");printf("[\"%s\",\"%s\",\"%s\",\"%s\",\"%s\"]",substr($1,1,7),$2,$3,$4,$6)}}' >> aux
  echo -n "]" >> aux
  myphoto=`cat aux`
  glen=`wc -l $fff | awk '{print $1}'`
  gend=$((gstart+glen-1))
  
  tok=`cat token`
  curl --request PUT -L \
  --header "Authorization: Bearer $tok" \
  --header "Content-Type: application/json" \
  --data '{"majorDimension":"ROWS","values":'$myphoto'}' \
  $'https://sheets.googleapis.com/v4/spreadsheets/1llfQf5gKJWKQ2v26qQWLik-P74F1QI2cu2iopM0uhC0/values/data!A'$gstart$':E'$gend$'?valueInputOption=RAW'
  
  gstart=$((gend+1))
done

tok=`cat token`
curl --request POST -L \
--header "Authorization: Bearer $tok" \
--header "Content-Type: application/json" \
--data '{"requests":[{"sortRange":{"range":{"sheetId":567133476,"startRowIndex":0,"startColumnIndex":0},"sortSpecs":[{"dataSourceColumnReference":{"name":"A"},"sortOrder":"ASCENDING"}]}}]}' "https://sheets.googleapis.com/v4/spreadsheets/1llfQf5gKJWKQ2v26qQWLik-P74F1QI2cu2iopM0uhC0:batchUpdate"
